from .cross_entropy import LabelSmoothingCrossEntropy, SoftTargetCrossEntropy, SoftTargetTemp
from .jsd import JsdCrossEntropy
from .asymmetric_loss import AsymmetricLossMultiLabel, AsymmetricLossSingleLabel